---
version: '3'
services:
  freqtrade:
    image: freqtradeorg/tradingbot:master
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./Dockerfile.technical"
    restart: unless-stopped
    container_name: tradingbot
    volumes:
      - "./user_data:/tradingbot/user_data"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /tradingbot/user_data/tradingbot.log
      --db-url sqlite:////tradingbot/user_data/tradesv3.sqlite
      --config /tradingbot/user_data/config.json
      --strategy SampleStrategy
