---
version: '3'
services:
  freqtrade_develop:
    build:
      context: .
      dockerfile: "./Dockerfile.develop"
    volumes:
      - ".:/tradingbot"
    entrypoint:
      - "tradingbot"

  freqtrade_bash:
    build:
      context: .
      dockerfile: "./Dockerfile.develop"
    volumes:
      - ".:/tradingbot"
    entrypoint:
      - "/bin/bash"
